<?xml version="1.0" encoding="UTF-8"?>
<kk:brkkadastralekaartCollection
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns:gml="http://www.opengis.net/gml/3.2"
        xmlns:kk="http://www.kadaster.nl/schemas/brkkadastralekaart/v4/featurecollection/v20190402"
        xmlns:oz="http://www.kadaster.nl/schemas/brkkadastralekaart/v4/imkad-onroerendezaak/v20190402"
        xmlns:h="http://www.kadaster.nl/schemas/brkkadastralekaart/v4/imkad-historie/v20190402"
        xmlns:t="http://www.kadaster.nl/schemas/brkkadastralekaart/v4/imkad-typen/v20190402"
        xmlns:ko="http://www.kadaster.nl/schemas/brkkadastralekaart/v4/imkad-kadastraalobject/v20190402"
        xsi:schemaLocation="http://www.kadaster.nl/schemas/brkkadastralekaart/v4/featurecollection/v20190402 http://www.kadaster.nl/schemas/brkkadastralekaart/v4/featurecollection/v20190402/brkkadastralekaart_v4_0_0.xsd"
        gml:id="NL.IMKAD.Kadastralekaart">
<kk:brkkadastralekaartMember>
    <oz:KadastraleGrens gml:id="NL.IMKAD.KadastraleGrens.230041151">
        <oz:historie>
            <h:beginGeldigheid>2006-08-11T15:55:45.000</h:beginGeldigheid>
            <h:tijdstipRegistratie>2006-08-11T15:55:45.000</h:tijdstipRegistratie>
            <h:volgnummer>0</h:volgnummer>
            <h:statusHistorie>
                <h:StatusHistorie>
                    <t:code>G</t:code>
                    <t:waarde>Geldig</t:waarde>
                </h:StatusHistorie>
            </h:statusHistorie>
        </oz:historie>
        <oz:identificatie>
            <t:namespace>NL.IMKAD.KadastraleGrens</t:namespace>
            <t:lokaalID>230041151</t:lokaalID>
        </oz:identificatie>
        <oz:grenslijn><gml:LineString xmlns:gml="http://www.opengis.net/gml/3.2" gml:id="GEOMETRY_ec197f37-fd52-4b3a-b70e-60da48fb4430" srsName="28992"><gml:posList>119282.363 481964.963 119288.454 481964.761</gml:posList></gml:LineString></oz:grenslijn>
        <oz:typeGrens>
            <oz:TypeGrens>
                <t:code>3</t:code>
                <t:waarde>Definitief</t:waarde>
            </oz:TypeGrens>
        </oz:typeGrens>
        <oz:perceelLinks>
            <t:namespace>NL.IMKAD.KadastraalObject</t:namespace>
            <t:lokaalID>11720047170000</t:lokaalID>
        </oz:perceelLinks>
        <oz:perceelRechts>
            <t:namespace>NL.IMKAD.KadastraalObject</t:namespace>
            <t:lokaalID>11720047070000</t:lokaalID>
        </oz:perceelRechts>
    </oz:KadastraleGrens>
</kk:brkkadastralekaartMember>
<kk:brkkadastralekaartMember>
    <oz:KadastraleGrens gml:id="NL.IMKAD.KadastraleGrens.230041152">
        <oz:historie>
            <h:beginGeldigheid>2006-08-11T15:55:45.000</h:beginGeldigheid>
            <h:tijdstipRegistratie>2006-08-11T15:55:45.000</h:tijdstipRegistratie>
            <h:volgnummer>0</h:volgnummer>
            <h:statusHistorie>
                <h:StatusHistorie>
                    <t:code>G</t:code>
                    <t:waarde>Geldig</t:waarde>
                </h:StatusHistorie>
            </h:statusHistorie>
        </oz:historie>
        <oz:identificatie>
            <t:namespace>NL.IMKAD.KadastraleGrens</t:namespace>
            <t:lokaalID>230041152</t:lokaalID>
        </oz:identificatie>
        <oz:grenslijn><gml:LineString xmlns:gml="http://www.opengis.net/gml/3.2" gml:id="GEOMETRY_742b104e-d8c4-4b73-a260-c07d4f314ed6" srsName="28992"><gml:posList>119282.378 481967.792 119282.394 481970.792</gml:posList></gml:LineString></oz:grenslijn>
        <oz:typeGrens>
            <oz:TypeGrens>
                <t:code>3</t:code>
                <t:waarde>Definitief</t:waarde>
            </oz:TypeGrens>
        </oz:typeGrens>
        <oz:perceelLinks>
            <t:namespace>NL.IMKAD.KadastraalObject</t:namespace>
            <t:lokaalID>11720046870000</t:lokaalID>
        </oz:perceelLinks>
        <oz:perceelRechts>
            <t:namespace>NL.IMKAD.KadastraalObject</t:namespace>
            <t:lokaalID>11720047270000</t:lokaalID>
        </oz:perceelRechts>
    </oz:KadastraleGrens>
</kk:brkkadastralekaartMember>
<kk:brkkadastralekaartMember>
    <oz:KadastraleGrens gml:id="NL.IMKAD.KadastraleGrens.230041153">
        <oz:historie>
            <h:beginGeldigheid>2006-08-11T15:55:45.000</h:beginGeldigheid>
            <h:tijdstipRegistratie>2006-08-11T15:55:45.000</h:tijdstipRegistratie>
            <h:volgnummer>0</h:volgnummer>
            <h:statusHistorie>
                <h:StatusHistorie>
                    <t:code>G</t:code>
                    <t:waarde>Geldig</t:waarde>
                </h:StatusHistorie>
            </h:statusHistorie>
        </oz:historie>
        <oz:identificatie>
            <t:namespace>NL.IMKAD.KadastraleGrens</t:namespace>
            <t:lokaalID>230041153</t:lokaalID>
        </oz:identificatie>
        <oz:grenslijn><gml:LineString xmlns:gml="http://www.opengis.net/gml/3.2" gml:id="GEOMETRY_fb77eba2-a1c4-454b-ad7b-3e0f865e2e73" srsName="28992"><gml:posList>119282.378 481967.792 119288.488 481967.760</gml:posList></gml:LineString></oz:grenslijn>
        <oz:typeGrens>
            <oz:TypeGrens>
                <t:code>3</t:code>
                <t:waarde>Definitief</t:waarde>
            </oz:TypeGrens>
        </oz:typeGrens>
        <oz:perceelLinks>
            <t:namespace>NL.IMKAD.KadastraalObject</t:namespace>
            <t:lokaalID>11720047270000</t:lokaalID>
        </oz:perceelLinks>
        <oz:perceelRechts>
            <t:namespace>NL.IMKAD.KadastraalObject</t:namespace>
            <t:lokaalID>11720047170000</t:lokaalID>
        </oz:perceelRechts>
    </oz:KadastraleGrens>
</kk:brkkadastralekaartMember>
<kk:brkkadastralekaartMember>
    <oz:KadastraleGrens gml:id="NL.IMKAD.KadastraleGrens.230041154">
        <oz:historie>
            <h:beginGeldigheid>2006-08-11T15:55:45.000</h:beginGeldigheid>
            <h:tijdstipRegistratie>2006-08-11T15:55:45.000</h:tijdstipRegistratie>
            <h:volgnummer>0</h:volgnummer>
            <h:statusHistorie>
                <h:StatusHistorie>
                    <t:code>G</t:code>
                    <t:waarde>Geldig</t:waarde>
                </h:StatusHistorie>
            </h:statusHistorie>
        </oz:historie>
        <oz:identificatie>
            <t:namespace>NL.IMKAD.KadastraleGrens</t:namespace>
            <t:lokaalID>230041154</t:lokaalID>
        </oz:identificatie>
        <oz:grenslijn><gml:LineString xmlns:gml="http://www.opengis.net/gml/3.2" gml:id="GEOMETRY_81c115a5-15dd-4e8b-8954-ed88b36b135c" srsName="28992"><gml:posList>119282.394 481970.792 119288.504 481970.760</gml:posList></gml:LineString></oz:grenslijn>
        <oz:typeGrens>
            <oz:TypeGrens>
                <t:code>3</t:code>
                <t:waarde>Definitief</t:waarde>
            </oz:TypeGrens>
        </oz:typeGrens>
        <oz:perceelLinks>
            <t:namespace>NL.IMKAD.KadastraalObject</t:namespace>
            <t:lokaalID>11720047370000</t:lokaalID>
        </oz:perceelLinks>
        <oz:perceelRechts>
            <t:namespace>NL.IMKAD.KadastraalObject</t:namespace>
            <t:lokaalID>11720047270000</t:lokaalID>
        </oz:perceelRechts>
    </oz:KadastraleGrens>
</kk:brkkadastralekaartMember>
<kk:brkkadastralekaartMember>
    <oz:KadastraleGrens gml:id="NL.IMKAD.KadastraleGrens.230041155">
        <oz:historie>
            <h:beginGeldigheid>2019-10-23T12:56:53.000</h:beginGeldigheid>
            <h:tijdstipRegistratie>2019-10-23T12:57:28.000</h:tijdstipRegistratie>
            <h:volgnummer>0</h:volgnummer>
            <h:statusHistorie>
                <h:StatusHistorie>
                    <t:code>G</t:code>
                    <t:waarde>Geldig</t:waarde>
                </h:StatusHistorie>
            </h:statusHistorie>
        </oz:historie>
        <oz:identificatie>
            <t:namespace>NL.IMKAD.KadastraleGrens</t:namespace>
            <t:lokaalID>230041155</t:lokaalID>
        </oz:identificatie>
        <oz:grenslijn><gml:LineString xmlns:gml="http://www.opengis.net/gml/3.2" gml:id="GEOMETRY_2867424d-1606-48fd-9715-67113b5e1018" srsName="28992"><gml:posList>119282.464 481973.926 119288.520 481973.890 119288.504 481970.760</gml:posList></gml:LineString></oz:grenslijn>
        <oz:typeGrens>
            <oz:TypeGrens>
                <t:code>3</t:code>
                <t:waarde>Definitief</t:waarde>
            </oz:TypeGrens>
        </oz:typeGrens>
        <oz:perceelLinks>
            <t:namespace>NL.IMKAD.KadastraalObject</t:namespace>
            <t:lokaalID>11720511170000</t:lokaalID>
        </oz:perceelLinks>
        <oz:perceelRechts>
            <t:namespace>NL.IMKAD.KadastraalObject</t:namespace>
            <t:lokaalID>11720047370000</t:lokaalID>
        </oz:perceelRechts>
    </oz:KadastraleGrens>
</kk:brkkadastralekaartMember>
</kk:brkkadastralekaartCollection>
