-- export adres_plus naar CVS (exclusief geopunt) 
copy(SELECT 
  adres_plus.openbareruimtenaam, 
  adres_plus.verkorteopenbareruimtenaam, 
  adres_plus.openbareruimte_id, 
  adres_plus.huisnummer, 
  adres_plus.huisletter, 
  adres_plus.huisnummertoevoeging, 
  adres_plus.postcode, 
  adres_plus.nummeraanduiding_id, 
  adres_plus.woonplaatsnaam AS woonplaats, 
  adres_plus.woonplaatscode, 
  adres_plus.gemeentenaam AS gemeente, 
  adres_plus.gemeentecode, 
  adres_plus.provincienaam, 
  adres_plus.provinciecode, 
  adres_plus.nevenadres, 
  adres_plus.typeadresseerbaarobject, 
  adres_plus.adresseerbaarobject_status, 
  adres_plus.opp_adresseerbaarobject_m2, 
  adres_plus.aantal_nad_per_adresobject, 
  adres_plus.adresseerbaarobject_id, 
  adres_plus.x, 
  adres_plus.y, 
  adres_plus.lon, 
  adres_plus.lat, 
  adres_plus.woonfunctie, 
  adres_plus.bijeenkomstfunctie, 
  adres_plus.celfunctie, 
  adres_plus.gezondheidszorgfunctie, 
  adres_plus.industriefunctie, 
  adres_plus.kantoorfunctie, 
  adres_plus.logiesfunctie, 
  adres_plus.onderwijsfunctie, 
  adres_plus.sportfunctie, 
  adres_plus.winkelfunctie, 
  adres_plus.overige_gebruiksfunctie, 
  adres_plus.aantal_pand_relaties_dit_vbo, 
  adres_plus.pand_id, 
  adres_plus.aantal_vbo_relaties_dit_pnd, 
  adres_plus.vbo_pnd_1_op_1, 
  adres_plus.opp_pand, 
  adres_plus.woningtype, 
  adres_plus.omtrek_pand, 
  adres_plus.verhouding_opp_vbo_opp_pnd, 
  adres_plus.pandstatus, 
  adres_plus.bouwjaar, 
  adres_plus.uniq_key, 
  adres_plus.pchnhlht, 
  adres_plus.pchnhlht_uniek, 
  adres_plus.pchn_uniek, 
  adres_plus.rangorde_pchn
FROM 
  bagactueel.adres_plus)  TO '/tmp/bagadresplus.csv' WITH CSV HEADER DELIMITER ';';


